apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hw
  name: hw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hw
    spec:
      containers:
      - image: hello-world
        name: hello-world
        resources: {}
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hw
  name: hw
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hw
  type: ClusterIP
status:
  loadBalancer: {}
