version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in  to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 885843804602.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=885843804602.dkr.ecr.us-west-2.amazonaws.com/spboot2020-1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 885843804602.dkr.ecr.us-west-2.amazonaws.com/spboot2020-1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"spboot2020-1","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/springboot-0.0.1-SNAPSHOT.jar
